### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by jer3m01** [thetarnav/solid-devtools#221]
Hi, it would be awesome if this extension was published on https://addons.mozilla.org.

I uploaded the `crx` file to https://www.extensiontest.com and it says the extension is compatible.

I don't have experience working on extensions so haven't tried anything further.

**Comment by thetarnav** [comment]
This interesting, thank you for checking the compatibility.
I preferred to focus only on chrome until the project is more mature, and I think that soon I'll have to look into that.
The tool that I'm using for bundling the extension ([a crxjs vite plugin](https://github.com/crxjs/chrome-extension-tools)) is mainly targeting chrome. So if it would work seemlesly in firefox, that would be amazing.

**Comment by Hanter666** [comment]
With the release of Solid JS 1.7.0, devtools has been stabilized as indicated. I hope the extension for firefox will be released soon )

**Comment by thetarnav** [comment]
I've actually switched to FF as my main browser, so now I have to 😄

**Comment by vedkothavade** [comment]
hey @thetarnav, any update on this?

**Comment by thetarnav** [comment]
[Looks like firefox support was added to crxjs.](https://github.com/crxjs/chrome-extension-tools/pull/644#issuecomment-1733540538) Still in beta but I'm gonna see how it goes.

**Comment by thetarnav** [comment]
Well some of it is working for sure. The content and background scripts, popup is working great, displaying solid version which means that the solid dubugger script was injected and communicates back, and devtools panel was added too, but it doesn't yet render anything.

![image](https://github.com/thetarnav/solid-devtools/assets/24491503/9f3c7489-357e-4655-a6e7-0940e9a20b0e)

**Comment by thetarnav** [comment]
👀
![Screenshot from 2023-11-05 20-32-17](https://github.com/thetarnav/solid-devtools/assets/24491503/542837fb-ece7-4bd4-8e86-bd7d5ca9a9da)

**Comment by thetarnav** [comment]
It seems that the firefox extension has been approved and it works for me when installed. If anyone wants to try it out: https://addons.mozilla.org/firefox/addon/solid-devtools
