### ISSUE TITLE
Solid not detected after following instructions

### ISSUE THREAD

**Issue by nikitavoloboev** [thetarnav/solid-devtools#227]
I have a solid start project together with solid-devtools setup here: https://github.com/nikitavoloboev/try/tree/main/solid

I followed instructions here: https://github.com/thetarnav/solid-devtools/tree/main/packages/extension#getting-started

But even after following them the extension is not detecting solid for me for some reason: 

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/6391776/223123224-a720981c-a612-4702-aee2-232bc2b1ddd3.png">

Not sure if I missed anything perhaps. My vite config looks like 

```
import solid from "solid-start/vite"
import { defineConfig } from "vite"
import devtools from "solid-devtools/vite"

export default defineConfig({
  plugins: [
    devtools({
      autoname: true,
      locator: {
        targetIDE: "vscode-insiders",
        componentLocation: true,
        jsxLocation: true,
      },
    }),
    solid(),
  ],
})
```

**Comment by tombohub** [comment]
same thing, not detected for solid start
