### ISSUE TITLE
Error -  No matching export in "node_modules/solid-js/web/dist/dev.js" for import "isDev"

### ISSUE THREAD

**Issue by anton-at-bay** [thetarnav/solid-devtools#228]
Getting the following error. Followed instruction to install the extension, npm package and added to vite plugins.

✘ [ERROR] No matching export in "node_modules/solid-js/web/dist/dev.js" for import "isDev"

    node_modules/@solid-primitives/utils/dist/index.js:3:9:
      3 │ export { isDev, isServer } from 'solid-js/web';
        ╵          ~~~~~

commenting out the plugin in vite.config removes the error and project compiles. 

Many thanks for help!

**Comment by thetarnav** [comment]
You probably need to update solid-js version. `isDev` export was added in `1.6.12` I think.

**Comment by anton-at-bay** [comment]
Many thanks! it works now 🙏
