### ISSUE TITLE
Overlay not work

### ISSUE THREAD

**Issue by Farnsi** [thetarnav/solid-devtools#230]
It shows only: `ReferenceError: Cannot access 'container9' before initialization`

Does it work with@solidjs/router and lazy loaded components?

![image](https://user-images.githubusercontent.com/31160860/229280710-60f95baa-c56a-49f1-9c29-981477542112.png)

Chrome version 111.0.5563.146
Linux Mint 21.1

What can i do to ship more/better details?

**Comment by thetarnav** [comment]
Thanks for the reports 🙏
Could you include your dependency versions? (solid, router)

**Comment by Calhistorian** [comment]
Same error:

`@solidjs/router: ^0.8.2`
`solid-js: v1.7.0`
`vite-plugin-solid: v2.7.0`

Though I am attempting to use in Electron.

**Comment by vsviridov** [comment]
Same issue after updating.
```
@solid-devtools/overlay 0.6.0 
solid-js 1.7.5
vite-plugin-solid 2.7.0
```

**Comment by yume-chan** [comment]
This is how the source code was written:

https://github.com/thetarnav/solid-devtools/blob/d0d7910e2b4acb709c698225a2819019fb253c2d/packages/frontend/src/modules/structure/Path.tsx#L17-L25

The problem might be that `createElementSize` used to call `target` in `onMount`, but now immediately:

https://github.com/solidjs-community/solid-primitives/commit/2f6d3732d4e0d18c2f123f90d9225e0924bcf765#diff-7b7a1aa744c704ff1f8a484e16ecc05716c8f6229ded8e7d5d3b2cd5606e18c5L210-L215
