### ISSUE TITLE
Use the browser extension to inject `<script type="module" src="/__solid-devtools"></script>`

### ISSUE THREAD

**Issue by brillout** [thetarnav/solid-devtools#233]
Currently, it's the Vite plugin `solid-devtools/vite` that injects the devtools `<script>` into the HTML.

But, as explained [here](https://github.com/brillout/vite-plugin-ssr/issues/402),  Vite's HTML transformers cannot be applied to SSR servers in production.

Is there a reason for not using the browser extension to inject the script instead of using the Vite plugin?

**Comment by thetarnav** [comment]
In the next version, I want to inject the debugger with the extensions you said. But a vite plugin will still be necessary.
1. I need to expose solid APIs to the debugger. This is what the virtual `__solid-devtools` file is mostly doing.
2. A vite plugin allows to apply custom code transforms in development to help with debugging.
3. It's the nicest way for configuring the debugger/extension. It's not used as much now, but for example, you can specify which editor should be opened when you try to open the component source code.

But I understand that point 1 is the main issue, and I don't like it as well. I'll have to find a different way of injecting the setup script that works with SSR as well.

**Comment by brillout** [comment]
Sounds good.

And, yes, the important thing here is that the Vite plugin shouldn't rely on an HTML transformer. FYI vite-plugin-ssr users cannot use solid-devtools because of that.

(Unrelated but it seems to me that `3.` should be configured on per-user basis inside the extension and not on a per-project basis by the Vite plugin.)

**Comment by brillout** [comment]
I'm not that familiar with browser extensions.

Alternatively, I'd expose the HTML transformer as a separate module to be loaded in production: `import { addDevtoolsScript } from 'solid-devtools/html-transformer'`. But, as a user not knowing why it's needed, I'd be wary of injecting a `<script>` for every user, even for the vast majority of users who don't use solid-devtools.

**Comment by felixhaeberle** [comment]
hey there, is there any plan for supporting this? 🙏

**Comment by thetarnav** [comment]
I'll experiment with different methods for the new version.
Not I know that transforming HTML isn't the best solution.

**Comment by felixhaeberle** [comment]
Thank you for your efforts, much appreciated, is there any possibility I can assist/help you?

**Comment by thetarnav** [comment]
@felixhaeberle If you have a minimal solid`vite-ssg` template laying around that I could use to test the devtools plugin I would really appreciate it 😁

**Comment by felixhaeberle** [comment]
@thetarnav Hey, there is this example by @brillout which you can use! :)
https://github.com/brillout/vite-plugin-ssr/tree/main/examples/solid-ssr/
Install instructions also in the README 👍
