### ISSUE TITLE
Followed instructions on solid start repository, does not work

### ISSUE THREAD

**Issue by nikitavoloboev** [thetarnav/solid-devtools#235]
The repo: https://github.com/nikitavoloboev/kuskus

I am not sure what I am doing wrong.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/6391776/233635492-9b7e3879-2325-4107-b5d8-842846e0bb2e.png">

**Comment by thetarnav** [comment]
I'm working on support for Solid so I'll come back to this after it's done. (#232)
I suspect that this is the reason anyway.
