### ISSUE TITLE
Black text over a black background in DevTools Overlay graph view

### ISSUE THREAD

**Issue by elliotwaite** [thetarnav/solid-devtools#242]
The graph view in the DevTools Overlay shows black text over a black background, making it hard to read the values. I can only see the values if I select the text.

<img width="724" alt="Screenshot 2023-06-03 at 6 37 53 AM" src="https://github.com/thetarnav/solid-devtools/assets/1767836/c036c1eb-19b2-4ae1-ad47-d62e1f4e857a">

<img width="725" alt="Screenshot 2023-06-03 at 6 38 04 AM" src="https://github.com/thetarnav/solid-devtools/assets/1767836/40587620-cdaa-4332-9776-b9d622558d59">

**Comment by thetarnav** [comment]
Thanks, the graph view doesn't lacks light-mode styles from what I see.

**Comment by elliotwaite** [comment]
Thanks! The updated version looks great.
