### ISSUE TITLE
Solid devtools Firefox extension

### ISSUE THREAD

**Issue by liligga** [thetarnav/solid-devtools#264]
Thank you for creating such amazing package. Just a small question: is Firefox extension planned? I am heavily using Mozilla Firefox at home, at work and on my phone. Thank you.

**Comment by thetarnav** [comment]
Firefox is planned, as long as it it won't add too much maintenance burden. Theoretically it shouldn't, I'm not doing anything chrome-specific in the extension I think. There is already an issue for it, so lets track progress there: https://github.com/thetarnav/solid-devtools/issues/221
