### ISSUE TITLE
detector error

### ISSUE THREAD

**Issue by j4k0xb** [thetarnav/solid-devtools#285]
This error happens on many sites like <https://youtube.com>:
```
detector.ts-ca0eb97c.js:12 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'firstElementChild')
    at detectSolid (detector.ts-ca0eb97c.js:12:37)
    at detector.ts-ca0eb97c.js:66:1
```
![image](https://github.com/thetarnav/solid-devtools/assets/55899582/d92d2de7-d53e-4b30-851e-1972d204c760)

Seems like the extension runs too early, before body exists

**Comment by thetarnav** [comment]
Fixed in https://github.com/thetarnav/solid-devtools/commit/358a15e43d73084ba68d3fd57af7e894d467de03
