### ISSUE TITLE
Broken links in README at NPM website

### ISSUE THREAD

**Issue by Robin40** [thetarnav/solid-devtools#291]
If you see the solid-devtools readme https://github.com/thetarnav/solid-devtools/tree/main/packages/main#readme at NPM (https://www.npmjs.com/package/solid-devtools), the links containing `/blob/` like [Follow this locator guide to know more](https://github.com/thetarnav/solid-devtools/blob/debugger#using-component-locator) throw 404 not found.

The links are not broken if you see the readme on github.

**Comment by thetarnav** [comment]
Thanks
my fault for using relative urls
