### ISSUE TITLE
Astro + solid-devtools: "Uncaught (in promise) TypeError: document.body is null"

### ISSUE THREAD

**Issue by lighth7015** [thetarnav/solid-devtools#292]
Good morning!

I'm attempting to use `solid-devtools` on a solid website, built with Solid on Vite 5, however I'm receiving this TypeError when trying to load the site using `solid-devtools` in Firefox-

```
Uncaught (in promise) TypeError: document.body is null
    detectSolid moz-extension://8dc0b69e-78b0-4727-aa28-7857a8a920ee/assets/detector.ts-ca0eb97c.js:12
    <anonymous> moz-extension://8dc0b69e-78b0-4727-aa28-7857a8a920ee/assets/detector.ts-ca0eb97c.js:66
```

**Comment by thetarnav** [comment]
Should be already fixed in https://github.com/thetarnav/solid-devtools/commit/358a15e43d73084ba68d3fd57af7e894d467de03
