### ISSUE TITLE
Refreshing the page makes DOM tree disappear

### ISSUE THREAD

**Issue by tl-luis** [thetarnav/solid-devtools#296]
devtools plugin version: #0.29.2.0_0.29.3/0.29.2
solid-devtools: 0.29.3
solid-js: 1.8.16

Whenever the devtools are opened with an entire DOM tree and the page is refreshed, the tree disappears completely. It only appears again once the inspector is closed and re-opened.

This happens on Firefox and Chrome on MacOS Sonoma 14.2.1.

**Comment by thetarnav** [comment]
Trying to solve this now
in the meantime I've found that "Reload Frame" from the panel ctx menu also helps with that

![image](https://github.com/user-attachments/assets/53cf543b-5ea2-4928-b964-54c47db0c49f)
