### ISSUE TITLE
Outdated solid-start peer dep causes peer deps issues with npm

### ISSUE THREAD

**Issue by florian-lefebvre** [thetarnav/solid-devtools#306]
Hi there! In `@astrojs/solid-js@4.2.0` I added support for `solid-devtools`, and added it as an optional peer dependency of the package.

However, it turns out that `solid-devtools` has a dependency on an older version of `solid-start`, which causes peer dependencies error when installing with `npm` (see https://github.com/withastro/astro/issues/11217). Do you think it could be possible to update it?

Thanks and let me know if/how I can help!

**Comment by thetarnav** [comment]
solid-start dependency is removed now in #317
