### ISSUE TITLE
Crashes in Firefox (loading before document?)

### ISSUE THREAD

**Issue by jda0** [thetarnav/solid-devtools#309]
I'm having no luck avoiding "Detector script failed to load." in Firefox 129.0.2.

I believe `loadScriptInRealWorld` may be called and trying to update the document head before Firefox loads the document, since it's not wrapped in an event handler (i.e. DOMContentLoaded). I may be incorrect - I'm using Solid Start.
https://github.com/thetarnav/solid-devtools/blob/59123330a26a3044de21b4e1d8a3139d8909f921/packages/extension/content/content.ts#L56

**Comment by thetarnav** [comment]
I'm hitting the same error now.
But after a page refresh the detector script is properly loaded.


https://github.com/user-attachments/assets/968208b3-49ba-4153-939b-d67a0e29f714

**Comment by thetarnav** [comment]
Ok with new version the error is a bit clearer and it is like you said, `document.head` is not present yet

![image](https://github.com/user-attachments/assets/640e5102-5521-409e-acf4-6c4168cbc198)

**Comment by thetarnav** [comment]
In 0.31.4 the script loads fine.
I'm appending the script to `document.documentElement` now when head is null.
But for some reason the element overlay for hovered components doesn't have a background?
It's gone after refresh too so it must be somehow related, but I have no idea whats going on yet.

![Screenshot from 2024-12-17 12-52-57](https://github.com/user-attachments/assets/e72f3567-7c9d-4d88-b4a5-31b2ccea9073)

**Comment by thetarnav** [comment]
Nvm that was just dark-reader
