### ISSUE TITLE
Breaks in Safari

### ISSUE THREAD

**Issue by Ehesp** [thetarnav/solid-devtools#33]
When using DevTools with Safari, it's throwing an `TypeError: Illegal constructor` error:

https://github.com/thetarnav/solid-devtools/blob/8277c2f05ef6cece24a6f3e284d771ea3cdc4aec/packages/ui/src/twind.ts#L13

```js
var sheet = cssomSheet({ target: new CSSStyleSheet() });
```

![image](https://user-images.githubusercontent.com/842078/179221382-0564ff69-9af0-4598-8b8e-ca2deb865024.png)

It's not supported in Safari yet - not a biggie for me, using a different browser for main development but found this when debugging another issue in Safari.

**Comment by thetarnav** [comment]
Ah, I wasn't aware, thank you.
The reason we've went with CSSStyleSheet and twind is to be able to easily inject styles into a shadow dom.
I guess I'll have to include a [polyfill](https://www.npmjs.com/package/construct-style-sheets-polyfill) for now, or look for completely another approach.
Wonder if there is a way to apply such polyfill only in dev though...

**Comment by Ehesp** [comment]
Could we do a dynamic import if it's in dev? Since this is only for dev I think a "hackier" approach would make sense rather than reinventing the wheel.
