### ISSUE TITLE
Attach the debugger in the extension content script

### ISSUE THREAD

**Issue by thetarnav** [thetarnav/solid-devtools#45]
After meging #25 users don't have to wrap their application with `<Debugger>` components, for it to be tracked.
Because of this, it should be theoretically possible to inject the debugger script *(that attaches the debugger into the reactive graph)* with the extension's content script.

Runtime npm library will still be available, and useful for some cases—for example configuring or adding babel plugins.

**Comment by thetarnav** [comment]
Ok, so there is a different problem that I didn't think of—loading the debugger by injecting a script tag effectively loads a second solid runtime on the page.

![image](https://user-images.githubusercontent.com/24491503/182851874-c1826987-be8a-4517-956d-248c7e4c233e.png)

This may be a problem, or maybe it won't—it depends if the debugger at any point will need to interact with the application's solid runtime. For example:
- when users want to register their own plugin.
- when the debugger would need to use some of solid's primitives to get information out of the application graph.

It would be great to be able to just install the extension and that's it, but I think we're stuck with an npm library approach. It's not that bad though.
In the future, we might go in a different direction, that provided a similar experience—there are couple of core solid members that would be happy to add the debugger to solid-start or even solid itself.

**Comment by myeon7** [comment]
So in regards to the use of <Debugger> components on the target application, would it now allow users to debug by running the <App>  and <Debugger> components side by side if users no longer need to warp the application? 

For instance, previously we needed to **<Debugger><App /><Debugger>** and have **debugComponent()** invoked inside the application to access updated root data for debugging purposes. With this new update, could we just do **<App /><Debugger/>** to access root data now? (I attached some screenshots below to show what I am referring to)

![previous debugger](https://user-images.githubusercontent.com/83806064/183150198-7c9b0a98-49e8-4efa-b9f1-cf757d631f83.png)
![inside target app](https://user-images.githubusercontent.com/83806064/183150208-ff483753-7be8-482c-940d-9b76d0678476.png)
![updated debugger](https://user-images.githubusercontent.com/83806064/183150212-bd11f97a-eee3-4777-886e-9e94d5d29503.png)

**Comment by thetarnav** [comment]
I'm closing this for now, as this isn't the direction I'll be going currently.
