### ISSUE TITLE
Try using `webext-bridge` for the app-extension messaging

### ISSUE THREAD

**Issue by thetarnav** [thetarnav/solid-devtools#46]
Using [`webext-bridge`](https://github.com/zikaari/webext-bridge) might help clean-up the logic or messaging between the runtime library on the client and the devtools panel.

**Comment by thetarnav** [comment]
Looks like this won't be possible before https://github.com/zikaari/webext-bridge/issues/7 is closed.

**Comment by zikaari** [comment]
You can use the `next` version - `yarn add webext-bridge@next`

**Comment by thetarnav** [comment]
Thank you. I'll try and let you how it went :)

**Comment by thetarnav** [comment]
@zikaari v6 works nicely, yet I think I'll go with wiring it up on my own for now. I like the "choose your destination" abstraction, so I'll just look for a way to implement it myself.
I can imagine this library working great for other projects, but in the case of devtools it might be a miss:
- HMR can cause the window namespace to be reassigned. resulting in an error
- I cannot guarantee that there will be someone listening for the messages—the runtime library and the devtools are decoupled. And missing message handler again results in an error.
- There were some ts issues that I believe https://github.com/zikaari/webext-bridge/pull/25 will resolve, but it wasn't a big problem
