### ISSUE TITLE
How to see the changes in signal?

### ISSUE THREAD

**Issue by outbackStack** [thetarnav/solid-devtools#62]
Thank for making this dev tools! I've been struggling with console.log to see my signals so far! LOL

Question: How can I see the signals after installing and adding this to the entry file?
```
import "solid-devtools"
// and that's it!
```

P.S I've found this package from
https://www.solidjs.com/blog/state-of-solid-july-2022

**Comment by thetarnav** [comment]
Hello again :)
Importing `"solid-devtools"` package is attaching the [debugger](https://github.com/thetarnav/solid-devtools/tree/main/packages/debugger) to your application and runs [extension-adapter](https://github.com/thetarnav/solid-devtools/tree/main/packages/extension-adapter). In other words, it is creating a platform for other devtools to use. It doesn't provide any functionality by itself really. I should make it clear in the docs, but it's all very work in progress.
You've mentioned `console.log`, then maybe you should look at the [logger](https://github.com/thetarnav/solid-devtools/tree/main/packages/logger#readme) package—it's using the debugger to log messages to the browser's console about state of signals/computations, etc.
Or see [locator](https://github.com/thetarnav/solid-devtools/tree/main/packages/locator#readme) to be able to locate the components on your page and go to their source code by clicking.
Those two are the currently available devtools. I'm mostly working on the chrome extension now, but it needs a lot of work still.

**Comment by outbackStack** [comment]
Thanks again @thetarnav :-)

I'm in the process of converting my app over from React and what I miss most is their chrome extension to see the state changes...

It's ok to use console.log for now as I don't want clog the browser console with too many more stuff! LOL

Good luck with this chrome extension project.

**Comment by thetarnav** [comment]
Try using https://suid.io/tools/react-to-solid codemod to get you halfway there.
I'm going to close this issue. Good luck with your app.
